version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redisYFinance
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379
      NODE_ENV: development # Set NODE_ENV to development
    ports:
      - "5001:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001
      NODE_ENV: development # Set NODE_ENV to development

  datafetcher:
    build: ./datafetcher
    container_name: datafetcher
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    env_file:
      - .env

volumes:
  postgres_data:
